### ISSUE TITLE
About  basic image Alpine！

### ISSUE THREAD

**Issue by JermineHu** [Scorpil/dockerfiles#15]
@Scorpil   Hi， Will Alpine be considered as a basic image in the future?

**Comment by Scorpil** [comment]
Hi. Absolutely. There's an [update about that](https://users.rust-lang.org/t/creating-official-docker-image-for-rust/4165/18?u=scorpil) I posted recently on rust users forum. I cannot say how soon it's gonna be here, but it's coming.
