### ISSUE TITLE
Feedback on the image

### ISSUE THREAD

**Issue by t-botz** [Scorpil/dockerfiles#3]
Hey,
Good work on building those images. I took inspiration from your repo to build my own image : 
https://hub.docker.com/r/thibaultdelor/docker-rust/

Here is a bit of feedback on your image : 
- Image too big, the /rust directory could be entirely removed
- Documentation is not needed either
- On build image doesn't use the standard /usr/src/app directory (not a big deal and not really a standard but a lot of images are conforming to that, nodejs, python, ...)
- On build image should have CMD before COPY to improve image caching
- Setting DEBIAN_FRONTEND=noninteractive in the environment is not necessary, it can cause problem if someone run your image with `docker run -ti`
- Having a beta and nightly tags seems to me that you are rebuilding the image for each changes.

Good work though! Hopefully we will have an official Rust image one day!

**Comment by Scorpil** [comment]
Thanks for very constructive feedback, it's appreciated.
