### ISSUE TITLE
incorrect versions/tags in hub.docker.com

### ISSUE THREAD

**Issue by kudrevatykh** [Scorpil/dockerfiles#8]
tag 1.13 and 1.13-onbuild have beta version of 1.13, not stable
```
docker run -it --rm scorpil/rust:1.13 rustc --version
rustc 1.13.0-beta.3 (106d18793 2016-11-04)
```
I think that tags `stable`,`1.13`,`latest`,`1` should tag to same image, but currently they have different sha256 sums and each image should be downloaded separatly

**Comment by Scorpil** [comment]
Version issue is fixed.
```
➜  ~ docker run -it --rm scorpil/rust:stable rustc --version
rustc 1.13.0 (2c6933acc 2016-11-07)
➜  ~ docker run -it --rm scorpil/rust:1.13 rustc --version
rustc 1.13.0 (2c6933acc 2016-11-07) 
```
Unfortunately, it's a bit harder point tags to the same image with current dockerhub automated build setup. I'm planning to abandon dockerhub automated builds in favor of building image on separate server. Once it's done i will make sure to point duplicated tags to same image.

**Comment by kudrevatykh** [comment]
thanks!
