### ISSUE TITLE
1.15 appears to be 1.14 actually

### ISSUE THREAD

**Issue by nazar-pc** [Scorpil/dockerfiles#9]
Both `1.15` and `nightly` tags currently report this:
```
root@9c993574d3a6:/rust# rustc --version
rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)
```

**Comment by marcusball** [comment]
I'm seeing this too. It seems to be one version behind for some reason. Building using this is resulting in `rustc 1.15.0-nightly (71c06a56a 2016-12-18)`, even though the most recent is `rustc 1.16.0-nightly (2782e8f8f 2017-01-12)`.

**Comment by Scorpil** [comment]
1.15 appears to be ok now
```
> docker run -ti scorpil/rust:1.15 rustc -V
rustc 1.15.0-beta.1 (d9a0f0df7 2016-12-19)
```

But you're right regarding 1.16, @marcusball . I've triggered rebuild for the nightly builds, let's see how it goes.

**Comment by Scorpil** [comment]
Ok, new automation script is here, so this kinds of problems hopefully should not occur anymore.
